import { StyleSheet } from "react-native";

import { theme } from "../../styles/theme";

export const styles = StyleSheet.create({
  primary: {
    marginTop: 20,
    width: 200,
    backgroundColor: theme.colors.white,
    paddingTop: 10,
    borderWidth: 1,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  secondary: {
    marginTop: 20,
    width: 225,
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    paddingTop: 15,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  tertiary: {
    marginTop: 20,
    width: 225,
    backgroundColor: "transparent",
    paddingTop: 15,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  primaryText: {
    fontFamily: theme.fonts.semibold,
    color: theme.colors.red,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: 16,
  },
  secondaryText: {
    fontFamily: theme.fonts.semibold,
    color: theme.colors.blue,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: 16,
  },
  tertiaryText: {
    fontFamily: theme.fonts.semibold,
    color: theme.colors.black,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: 16,
  },
  nextIcon: {
    marginLeft: 50,
  },
});
